### ISSUE TITLE
Uniformed code style

### ISSUE THREAD

**Issue by heitaoflower** [exezin/exengine-testing#10]
I see your some of functions, the return type defined bool, however you alway use 0 or 1 as the return value.

maybe you should include #include <stdbool.h> , instead of 0 or 1 with true or false.

above all, just my personal advice. 

last but not the least, I like you project.

**Comment by solenum** [comment]
Personally I'm not big on the use of stdbool.h as it's just a typedef for 1 and 0 anyway, I think there are at most a few instances of an actual 'bool' type being used in the exengine source.  I'll probably change them to be an int-type.
