### ISSUE TITLE
replace imgui with nuklear

### ISSUE THREAD

**Issue by monolifed** [exezin/exengine-testing#17]
Pros:
single header lib in C
Cons:
lacks some features (?)

**Comment by solenum** [comment]
I think functionality-wise, imgui is considerably superior.  Though imgui is really just a debugging GUI library, while nuklear seems more viable for game GUI's. 

I was planning on removing imgui or at the very least making it optional as I dislike depending on a c++ compiler.  I might add in nuklear as an extra optional thing somewhere down the line so keep this issue open until then.
