### ISSUE TITLE
OpenGL ES 2.0 / WebGL (v1) Back-porting

### ISSUE THREAD

**Issue by ghost** [exezin/exengine-testing#2]
Could ExEngine be back-ported to OpenGL ES 2.0 / WebGL (v1) to support older browsers and devices? If so, would it involve re-writing the shaders, or are there specific OpenGL ES 3.0 / WebGL2 calls being made by the engine?

**Comment by solenum** [comment]
I think this issue might be better suited for [exengine-web](https://github.com/exezin/exengine-web) as core (exengine-testing) doesn't target GLES/WebGL.

Either way, porting to GLES 2 (and thus WebGL 1) wouldn't be that difficult, the majority of changes required would be in the shaders.  Consider opening an issue on that repository and I'll look into adding GLES 2 support when I can :)

Edit;
I went ahead and opened the issue for you, feel free to discuss it there exezin/exengine-web#1
