### ISSUE TITLE
Deferred renderer setting not working

### ISSUE THREAD

**Issue by JordanBlythe** [exezin/exengine-testing#7]
Unfortunately all I'm getting is a black screen, it works fine in forward rendering mode and the imgui stuff still renders, not sure why this is happening so figured I'd let you know.

**Comment by solenum** [comment]
What hardware are you running it on? (Also what OS, etc..)

**Comment by solenum** [comment]
@JordanBlythe Any update on this?

**Comment by solenum** [comment]
Can't replicate the issue myself and have no other information to go on so I'm closing this issue for now.
