### ISSUE TITLE
Player Properties

### ISSUE THREAD

**Issue by ghost** [exezin/exengine-testing#8]
Where can I find and modify player properties?

**Comment by solenum** [comment]
I assume you're referring to the included demo?  If so, the 'properties' for the player (such as the move speed and jump height) are sort of strewn across main.c.  If you aren't referring to the demo, well.. the engine has no concept of a 'player', just entities that you can move around in the scene, cameras that you can place, etc.

**Comment by ghost** [comment]
Thanks!
